version: '3.9'

services:
  postgres:
    image: postgres:15
    restart: always
    env_file:
      - .env
    volumes:
      - ./silo_postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - shared-network

  server:
    restart: always
    build:
      context: server
      dockerfile: Dockerfile
    env_file:
      - .env
    ports:
      - "8000:8000"
    depends_on:
      - postgres
    networks:
      - shared-network

  client:
    restart: unless-stopped
    build:
      context: client
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    networks:
      - shared-network
    depends_on:
      - server
    volumes:
      - ./client/app:/usr/src/client/app
      - ./client/public:/usr/src/client/public

networks:
  shared-network:
